import { ReactElement } from 'react';
import { Button } from '@ui/buttons';
import Head from 'next/head';
import { Layout } from 'src/layouts';

import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="container  mx-auto h-60 bg-gray-50">
        <h1>Tailwindcss, nextjs, typescript && class-variance-authority</h1>
        <Button size="sm">Submit</Button>
        <Button size="md">Submit</Button>
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
